spring.application.name=api-gateway
server.port=8080

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=false

# JWT Configuration (debe coincidir con usuario-service)
jwt.secret=mySecureSecretKeyForTiendaGenericaWithMinimumLengthRequiredForHS256

springdoc.swagger-ui.urls[0].name=usuario-service
springdoc.swagger-ui.urls[0].url=/api/usuarios/v3/api-docs

springdoc.swagger-ui.urls[1].name=cliente-service
springdoc.swagger-ui.urls[1].url=/api/clientes/v3/api-docs

springdoc.swagger-ui.urls[2].name=producto-service
springdoc.swagger-ui.urls[2].url=/api/productos/v3/api-docs

springdoc.swagger-ui.urls[3].name=proveedor-service
springdoc.swagger-ui.urls[3].url=/api/proveedores/v3/api-docs

springdoc.swagger-ui.urls[4].name=venta-service
springdoc.swagger-ui.urls[4].url=/api/ventas/v3/api-docs

springdoc.swagger-ui.urls[5].name=detalle-venta-service
springdoc.swagger-ui.urls[5].url=/api/detalles-venta/v3/api-docs
