spring.jpa.database = MYSQL
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:// equipo9pruebas68. xxxxxxxxxxxxxxxxxxxx.us-east2.rds.amazonaws.com:3306/tiendagenerica?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacy
spring.datasource.username=admin
spring.datasource.password=admin123
server.port=5000

