spring.application.name=detalle-venta-service
server.port=8086

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true

spring.jpa.database = MYSQL
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://192.168.1.13:3306/tiendagenerica_detalleventa
spring.datasource.username=admin_detalleventa
spring.datasource.password=admin12345
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
springdoc.api-docs.path=/api/detalles-venta/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
