spring.application.name=producto-service
server.port=8083

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true

spring.jpa.database = MYSQL
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://192.168.0.21:3306/tiendagenerica_producto
spring.datasource.username=admin_producto
spring.datasource.password=admin12345
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
springdoc.api-docs.path=/api/productos/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
